# Enable Netlify's Next.js support (SSR, ISR, image optimization, etc.)
[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
  # relative path to the folder that contains your Next.js app (where package.json lives)
  base    = "split_easy_updated"

  # regenerate Prisma client, then build
  command = "npx prisma generate && npm run build"

